#!/usr/bin/env python3
import argparse
import os

from utils import Args, Funcs
from retrieval import Retrieval
from incidence_matrix import IncidenceMatrix

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-q', type=str, default='topics-train_cs.xml', help='Topics list file')
    parser.add_argument('-d', type=str, default='documents_cs.lst', help='Documents list file')
    parser.add_argument('-r', type=str, default='run-0_cs', help='Run name')
    parser.add_argument('-o', type=str, default='cs_baseline.res', help='Output file')
    parser.add_argument('-document_path', type=str, default='documents_cs', help='Path to folder with documents')

    args_inline = parser.parse_args()
    # all arguments for the run
    args = Args(args_inline)
    im = IncidenceMatrix.create(args)
    # im.save(args)
    retrieval = Retrieval(im, args)
    retrieval.perform_retrieval()
